import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "tertiary-fixed-dim": "#c084fc",
        "secondary-fixed-dim": "#94a3b8",
        "on-secondary-fixed": "#0f172a",
        primary: "#135bec",
        "secondary-container": "#1e293b",
        "surface-variant": "#0f172a",
        "surface-dim": "#0b0d11",
        outline: "#334155",
        error: "#ef4444",
        "secondary-fixed": "#e2e8f0",
        "inverse-surface": "#f6f6f8",
        tertiary: "#c084fc",
        "surface-bright": "#1d1f28",
        "on-surface": "#ffffff",
        "on-tertiary-fixed-variant": "#581c87",
        "on-primary-fixed": "#00174c",
        "on-tertiary-fixed": "#2e1065",
        "surface-tint": "#135bec",
        "primary-container": "#135bec",
        "on-secondary-container": "#cbd5e1",
        "error-container": "#7f1d1d",
        "on-tertiary": "#ffffff",
        "outline-variant": "#1e293b",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#0b0d11",
        "on-primary-container": "#e2e6ff",
        "primary-fixed": "#dbe1ff",
        "on-error-container": "#fee2e2",
        "on-secondary-fixed-variant": "#334155",
        "surface-container-lowest": "#07080a",
        "on-background": "#ffffff",
        secondary: "#334155",
        "tertiary-container": "#581c87",
        "tertiary-fixed": "#f5f3ff",
        // background: "#0b0d11",
        "surface-container-high": "#191b24",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#003daa",
        "inverse-primary": "#b4c5ff",
        "surface-container-highest": "#282a32",
        surface: "#0b0d11",
        "on-surface-variant": "#94a3b8",
        "on-tertiary-container": "#f5f3ff",
        "surface-container-low": "#0b0d11",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container": "#11131b",
        "on-error": "#ffffff",
      },
    },
  },
  plugins: [],
};

export default config;
