import Navigation from "@/components/ui/Navigation";
import { getServerSession } from "@/lib/session";
import { redirect } from "next/navigation";
import { BiBulb, BiSolidBarChartSquare } from "react-icons/bi";
import {
  BsCopy,
  BsDiagram2Fill,
  BsFileEarmarkRichtext,
  BsFillPenFill,
  BsFillShareFill,
  BsStars,
} from "react-icons/bs";

const ExplanationPage = async () => {
  const session = await getServerSession();

  if (!session?.user) {
    redirect("/login");
  }

  return (
    <div className="w-full bg-background-light dark:bg-background-dark text-slate-900 dark:text-slate-100 min-h-screen">
      <Navigation />
      <main className="max-w-5xl mx-auto p-4 pb-32 space-y-6">
        <section className="bg-white dark:bg-slate-900 rounded-xl p-4 border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold uppercase tracking-wider text-white dark:text-slate-400">
              Original Snippet
            </span>
            <button className="flex items-center gap-1 text-primary text-sm font-semibold">
              <BsFillPenFill className="text-xs" />
              Edit
            </button>
          </div>
          <div className="bg-slate-50 dark:bg-slate-950 rounded-lg p-3 overflow-hidden">
            <code className="code-font text-sm text-slate-700 dark:text-slate-300 block truncate">
              const fetchUserData = async (id) =&gt; &#x7B; return await
              db.users.findUnique(&#x7B; where: &#x7B; id &#x7D; &#x7D;); &#x7D;
            </code>
          </div>
        </section>

        <section className="space-y-4 mt-10">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-lg bg-blue-500 flex items-center justify-center text-primary">
              <BsStars className="text-md" />
            </div>
            <div>
              <h2 className="text-xl font-bold">AI Analysis</h2>
              <p className="text-xs text-slate-500">
                Generated by GPT-4o • 1.2s
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800">
              <p className="text-xs text-slate-500 mb-1">Complexity</p>
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold">Low</span>
                <span className="size-2 rounded-full bg-green-500"></span>
              </div>
            </div>
            <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800">
              <p className="text-xs text-slate-500 mb-1">Language</p>
              <p className="text-lg font-bold">TypeScript</p>
            </div>
          </div>
        </section>

        <article className="prose prose-slate dark:prose-invert max-w-none space-y-6">
          <div>
            <h3 className="text-lg font-bold flex items-center gap-2 mb-2">
              <BsFileEarmarkRichtext className="text-md bg-primary" />
              Summary
            </h3>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              This function is an asynchronous utility designed to retrieve a
              single user record from a database using the{" "}
              <span className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                Prisma
              </span>{" "}
              ORM syntax. It targets a unique identifier and returns the user
              object or null if not found.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-bold flex items-center gap-2 mb-2">
              <BsDiagram2Fill className="text-md" />
              Step-by-Step
            </h3>
            <ul className="space-y-4 text-slate-600 dark:text-slate-400">
              <li className="flex gap-3">
                <span className="flex-none flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-xs font-bold">
                  1
                </span>
                <span>
                  Defines an arrow function{" "}
                  <code className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                    fetchUserData
                  </code>{" "}
                  that accepts a single parameter{" "}
                  <code className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                    id
                  </code>
                  .
                </span>
              </li>

              <li className="flex gap-3">
                <span className="flex-none flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-xs font-bold">
                  2
                </span>
                <span>
                  Uses the{" "}
                  <code className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                    async
                  </code>{" "}
                  keyword, allowing for non-blocking database operations using{" "}
                  <code className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                    await
                  </code>
                  .
                </span>
              </li>

              <li className="flex gap-3">
                <span className="flex-none flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-xs font-bold">
                  3
                </span>
                <span>
                  Calls{" "}
                  <code className="code-font text-xs bg-slate-100 dark:bg-slate-800 px-1 rounded">
                    db.users.findUnique
                  </code>
                  , which is optimized for primary key or unique constraint
                  lookups.
                </span>
              </li>
            </ul>
          </div>

          <div className="bg-primary/5 border border-primary/20 rounded-xl p-4">
            <h3 className="text-sm font-bold text-primary flex items-center gap-2 mb-2 uppercase tracking-tight">
              <BiBulb className="text-3xl" />
              Optimization Tip
            </h3>
            <p className="text-sm text-slate-700 dark:text-slate-300">
              Consider adding a <strong>try/catch</strong> block to handle
              potential database connection errors or timeouts gracefully.
            </p>
          </div>
        </article>

        <div className="rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800">
          <div className="h-32 bg-blue-500/30 dark:from-slate-800 dark:bg-blue-800/30 flex items-center justify-center relative">
            <div className="flex flex-col items-center relative z-10">
              <div className="text-center">
                <BiSolidBarChartSquare className="text-3xl mb-1 bg-primary" />
              </div>
              <p className="text-[14px] font-medium opacity-60">
                Performance impact: Negligible
              </p>
            </div>
          </div>
        </div>
      </main>

      <div className="bg-gradient-to-t from-background-light dark:from-background-dark via-background-light dark:via-background-dark to-transparent pt-5 pb-6 px-4">
        <div className="max-w-5xl mx-auto grid grid-cols-2 gap-3">
          <button className="flex items-center justify-center gap-2 h-14 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 font-bold hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors shadow-lg">
            <BsFillShareFill className="text-sm" />
            Share
          </button>

          <button className="flex items-center justify-center gap-2 h-14 rounded-xl bg-blue-500 text-white font-bold hover:opacity-90 transition-opacity shadow-lg shadow-primary/20">
            <BsCopy className="text-sm" />
            Copy
          </button>
        </div>
      </div>
    </div>
  );
};

export default ExplanationPage;
