import type { Metadata } from "next";
import Navigation from "@/components/ui/Navigation";
import { getServerSession } from "@/lib/session";
import { Explanation } from "@/lib/types";
import { createNoIndexMetadata } from "@/lib/seo";
import { redirect } from "next/navigation";
import { BiBulb, BiSolidBarChartSquare } from "react-icons/bi";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
// import SyntaxHighlighter from "react-syntax-highlighter";
// import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
// import { dark } from "react-syntax-highlighter/dist/esm/styles/prism";
// import { dracula } from "react-syntax-highlighter/dist/esm/styles/prism";
// import { materialDark } from "react-syntax-highlighter/dist/esm/styles/prism";

import { BsDiagram2Fill, BsFileEarmarkRichtext, BsStars } from "react-icons/bs";

import { cookies } from "next/headers";
import { parseBackticks } from "@/utils/helpers";

export const metadata: Metadata = createNoIndexMetadata(
  "Explanation Detail",
  "View a private, saved CodeAI explanation with summaries, steps, and performance insights.",
);

const ExplanationPage = async ({
  params,
}: {
  params: Promise<{ id: bigint }>;
}) => {
  const session = await getServerSession();

  const cookieStore = await cookies();
  const cookieHeader = cookieStore.toString();

  if (!session?.user) {
    redirect("/login");
  }

  const { id } = await params;

  const data = await fetch(
    `${process.env.NEXT_PUBLIC_APP_URL!}/api/explanations/${id}`,
    {
      headers: {
        cookie: cookieHeader,
      },
      cache: "no-store",
    },
  );

  const explanation = (await data.json()) as Explanation;

  return (
    <div className="w-full bg-background-light dark:bg-background-dark text-slate-900 dark:text-slate-100 min-h-screen">
      <Navigation />
      <main className="max-w-5xl mx-auto p-4 pb-32 space-y-6">
        <section className="bg-white dark:bg-slate-900 rounded-xl p-4 border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-semibold uppercase tracking-wider text-white dark:text-slate-400">
              Original Snippet
            </span>
          </div>
          <div className="bg-slate-50 dark:bg-slate-950 rounded-lg p-3 overflow-hidden">
            <SyntaxHighlighter
              style={vscDarkPlus}
              language={explanation.language}
              showLineNumbers={true}
              useInlineStyles={true}
              className="bg-slate-950"
            >
              {explanation.code}
            </SyntaxHighlighter>
          </div>
        </section>

        <section className="space-y-4 mt-10">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-lg bg-blue-500 flex items-center justify-center text-primary">
              <BsStars className="text-md" />
            </div>
            <div>
              <h2 className="text-xl font-bold">AI Analysis</h2>
              <p className="text-xs text-slate-500">
                Generated by {explanation.model} • 1.2s
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800">
              <p className="text-xs text-slate-500 mb-1">Complexity</p>
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold">
                  {explanation.complexity.charAt(0).toUpperCase() +
                    explanation.complexity.slice(1).toLocaleLowerCase()}
                </span>
                <span className="size-2 rounded-full bg-green-500"></span>
              </div>
            </div>
            <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800">
              <p className="text-xs text-slate-500 mb-1">Language</p>
              <p className="text-lg font-bold">{explanation.language}</p>
            </div>
          </div>
        </section>

        <article className="prose prose-slate dark:prose-invert max-w-none space-y-6">
          <div>
            <h3 className="text-lg font-bold flex items-center gap-2 mb-2">
              <BsFileEarmarkRichtext className="text-md bg-primary" />
              Summary
            </h3>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed text-md">
              {parseBackticks(explanation.longSummary)}
            </p>
          </div>

          <div>
            <h3 className="text-lg font-bold flex items-center gap-2 mb-2">
              <BsDiagram2Fill className="text-md" />
              Step-by-Step
            </h3>
            <ul className="space-y-4 text-slate-600 dark:text-slate-400">
              {explanation.explanation_steps &&
                explanation.explanation_steps.map((step) => (
                  <li className="flex gap-3" key={`#id-${step.step_number}`}>
                    <span className="flex-none flex items-center justify-center size-6 rounded-full bg-primary/10 text-primary text-xs font-bold">
                      {step.step_number}
                    </span>
                    <span>{parseBackticks(step.text)}</span>
                  </li>
                ))}
            </ul>
          </div>

          <div className="bg-primary/5 border border-primary/20 rounded-xl p-4">
            <h3 className="text-sm font-bold text-primary flex items-center gap-2 mb-2 uppercase tracking-tight">
              <BiBulb className="text-3xl" />
              Optimization Tip
            </h3>
            <p className="text-sm text-slate-700 dark:text-slate-300">
              {explanation.optimization_tip
                ? explanation.optimization_tip
                : "None"}
            </p>
          </div>
        </article>

        <div className="rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800">
          <div className="h-32 bg-blue-500/30 dark:from-slate-800 dark:bg-blue-800/30 flex items-center justify-center relative">
            <div className="flex flex-col items-center relative z-10">
              <div className="text-center">
                <BiSolidBarChartSquare className="text-3xl mb-1 bg-primary" />
              </div>
              <p className="text-[14px] font-medium opacity-60">
                Performance impact: {explanation.performance_impact}
              </p>
            </div>
          </div>
        </div>
      </main>

      {/* <div className="bg-gradient-to-t from-background-light dark:from-background-dark via-background-light dark:via-background-dark to-transparent pt-5 pb-6 px-4">
        <div className="max-w-5xl mx-auto grid grid-cols-2 gap-3">
          <button className="flex items-center justify-center gap-2 h-14 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 font-bold hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors shadow-lg">
            <BsFillShareFill className="text-sm" />
            Share
          </button>

          <button className="flex items-center justify-center gap-2 h-14 rounded-xl bg-blue-500 text-white font-bold hover:opacity-90 transition-opacity shadow-lg shadow-primary/20">
            <BsCopy className="text-sm" />
            Copy
          </button>
        </div>
      </div> */}
    </div>
  );
};

export default ExplanationPage;
